### ISSUE TITLE
Dispalying an event as a list in homescreen

### ISSUE THREAD

**Issue by FuadCd** [CMPUT301F24nocode/nocode-events#50]

**Comment by FuadCd** [comment]
The events are being displayed in the homescreen and clicking the event will redirect a user to the user landing page and organiser to organiser landing page

**Comment by ashra1-ai** [comment]
### Acceptance Criteria
**Event Display on Home Screen**

- The home screen displays a list of all available events.
- Each event item in the list shows:
- Event name
- Event date (formatted as DD-MM-YYYY)
- Event price (or "Free" if the price is zero)
- Events are displayed in a vertical list, with each item clearly separated.
- Clickable Event Items

### Each event item on the home screen is clickable.

- When a user clicks on an event, they are redirected based on their role:
- User Role: Redirect to the EventLandingPageUserActivity.
- Organizer Role: Redirect to the EventLandingPageOrganizerActivity.
- Redirect to User Landing Page
- EventLandingPageUserActivity for Regular Users

### If the logged-in user is a regular user, clicking an event on the home screen opens EventLandingPageUserActivity.

- This screen shows the following event details:
- Event name, details, rules, deadline, start date, and price.
- Number of attendees and optional entrants, if available.
- Geolocation requirement warning if geolocationEnabled is true.
- The user sees a Join button:
- Clicking Join adds the user to the event’s entrant list in Firestore.
- The Join button changes to Leave, allowing the user to remove themselves from the entrant list.
- Long-pressing the Leave button shows a confirmation dialog before removing the user.
- Geolocation Warning

### If geolocationEnabled is set to true in Firestore:
- A warning message displays above the Join button, informing the user that geolocation is required to join the event.
- If geolocationEnabled is false:
- The warning message is hidden, and no additional geolocation confirmation is required.
